<a href="https://colab.research.google.com/github/devinammar/googlecolab_machinelearning/blob/main/PM_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Library

import pandas as pd

# 1. Load Data
# Data WDBC gapunya header, jadi kita definisikan kolomnya
cols = ['ID', 'Diagnosis'] + [f'Feature_{i}' for i in range(1, 31)]
df = pd.read_csv('wdbc.data', header=None, names=cols)

# 2. Cek Informasi buat Worksheet
print("--- JAWABAN WORKSHEET (Breast Cancer) ---")
print(f"1. Nama Dataset : Breast Cancer (WDBC)")
print(f"2. Jumlah Sample: {df.shape[0]}")
print(f"3. Jumlah Fitur : {df.shape[1] - 2} (ID & Diagnosis bukan fitur)")
print(f"4. Target       : Diagnosis (M=Malignant, B=Benign)")
print(f"5. Tipe Problem : Biner\n")

print("--- ANALISIS MISSING VALUE ---")
missing = df.isnull().sum().sum()
print(f"1. Ada missing value? {'Yes' if missing > 0 else 'No'}")
print(f"2. Total missing: {missing}")

--- JAWABAN WORKSHEET (Breast Cancer) ---
1. Nama Dataset : Breast Cancer (WDBC)
2. Jumlah Sample: 569
3. Jumlah Fitur : 30 (ID & Diagnosis bukan fitur)
4. Target       : Diagnosis (M=Malignant, B=Benign)
5. Tipe Problem : Biner

--- ANALISIS MISSING VALUE ---
1. Ada missing value? No
2. Total missing: 0

In [2]:
# Load Dataset

# Load dataset WDBC
# Kita kasih nama kolom karena file .data aslinya gapunya header
cols = ['ID', 'Diagnosis'] + [f'Feature_{i}' for i in range(1, 31)]
df = pd.read_csv('wdbc.data', header=None, names=cols)

# Tampilkan 5 data teratas buat mastiin udah masuk
df.head()

,ID,Diagnosis,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,...,Feature_21,Feature_22,Feature_23,Feature_24,Feature_25,Feature_26,Feature_27,Feature_28,Feature_29,Feature_30
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [3]:
# --- B. Analisis Missing Value ---
print(f"Total Missing Value: {df.isnull().sum().sum()}")

# --- C. Categorical Encoding ---
# Ubah M (Malignant) jadi 1 dan B (Benign) jadi 0
df['Diagnosis'] = df['Diagnosis'].map({'M': 1, 'B': 0})
print("Encoding: Diagnosis berhasil diubah ke angka (M=1, B=0)")

# --- D. Feature Scaling ---
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Ambil fitur aja (ID dan Diagnosis jangan di-scale)
fitur_cols = df.columns[2:]
df[fitur_cols] = scaler.fit_transform(df[fitur_cols])

print("Scaling: Semua fitur sudah di-standarisasi dengan StandardScaler")

Total Missing Value: 0
Encoding: Diagnosis berhasil diubah ke angka (M=1, B=0)
Scaling: Semua fitur sudah di-standarisasi dengan StandardScaler

## Pertanyaan :
1. Berapa jumlah fitur? 30 fitur (ID dan Diagnosis tidak dihitung fitur).
2. Apa arti target? Status tumor, yaitu M (Malignant/Ganas) atau B (Benign/Jinak).

In [4]:
# Informasi Dataset (1)
df.shape

(569, 32)

In [5]:
# Informasi Dataset (2)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          569 non-null    int64
 1   Diagnosis   569 non-null    int64
 2   Feature_1   569 non-null    float64
 3   Feature_2   569 non-null    float64
 4   Feature_3   569 non-null    float64
 5   Feature_4   569 non-null    float64
 6   Feature_5   569 non-null    float64
 7   Feature_6   569 non-null    float64
 8   Feature_7   569 non-null    float64
 9   Feature_8   569 non-null    float64
 10  Feature_9   569 non-null    float64
 11  Feature_10  569 non-null    float64
 12  Feature_11  569 non-null    float64
 13  Feature_12  569 non-null    float64
 14  Feature_13  569 non-null    float64
 15  Feature_14  569 non-null    float64
 16  Feature_15  569 non-null    float64
 17  Feature_16  569 non-null    float64
 18  Feature_17  569 non-null    float64
 19  Feature_18  569 non-null    float64
 20  Feature_19  569 non-null    float64
 21  Feature_20  569 non-null    float64
 22  Feature_21  569 non-null    float64
 23  Feature_22  569 non-null    float64
 24  Feature_23  569 non-null    float64
 25  Feature_24  569 non-null    float64
 26  Feature_25  569 non-null    float64
 27  Feature_26  569 non-null    float64
 28  Feature_27  569 non-null    float64
 29  Feature_28  569 non-null    float64
 30  Feature_29  569 non-null    float64
 31  Feature_30  569 non-null    float64
dtypes: float64(30), int64(2)
memory usage: 142.4 KB

## Pertanyaan:
1. Berapa jumlah sampel?
2. Semua fitur numerik?
3. Ada missing?

In [6]:
# Periksa Missing Value

df.isnull().sum()

ID            0
Diagnosis     0
Feature_1     0
Feature_2     0
Feature_3     0
Feature_4     0
Feature_5     0
Feature_6     0
Feature_7     0
Feature_8     0
Feature_9     0
Feature_10    0
Feature_11    0
Feature_12    0
Feature_13    0
Feature_14    0
Feature_15    0
Feature_16    0
Feature_17    0
Feature_18    0
Feature_19    0
Feature_20    0
Feature_21    0
Feature_22    0
Feature_23    0
Feature_24    0
Feature_25    0
Feature_26    0
Feature_27    0
Feature_28    0
Feature_29    0
Feature_30    0
dtype: int64

## Pertanyaan
JAdi apakah perlu handling missing value?

In [7]:
# Distribusi Label

df["target"].value_counts()

KeyError: 'target'

In [ ]:
sns.countplot(x="target", data=df)
plt.title("Class Distribution")
plt.show()

In [ ]:
# hitung proporsi
df["target"].value_counts(normalize=True)

## Pertanyaan

1. Apakah dataset ini imbalanced?
2. Jika ya/tidak, kenapa?

In [ ]:
# Periksa Skala Fitur

df.describe()

Pertanyaan :
1. Apakah semua fitur memiliki skala serupa?
2. Lihat perbedaan mean dan std

In [ ]:
# Visualisasi 2 fitur

plt.figure(figsize=(8,4))
plt.hist(df["mean radius"], bins=30, alpha=0.6, label="mean radius")
plt.hist(df["mean area"], bins=30, alpha=0.6, label="mean area")
plt.legend()
plt.show()

Pertanyaan:
1. APakah perlu scaling?
2. model yang bagaiana yang memerlukan scaling?

In [ ]:
# KOrelasi fitur

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), cmap="coolwarm", center=0)
plt.title("Feature Correlation Matrix")
plt.show()

jika korelasi tinggi dengan target/label.. patut dicurigai ada fitur turunan langsung dengan target